cmtsolutions:
  - class: File
    path: data/CF1/CMTSOLUTION
  - class: File
    path: data/CF2/CMTSOLUTION
interpolation:
  processes: 32
  script:
    class: File
    path: scripts/mpi_moviedata2vtk.py
  step: 1000
meshdir:
  class: Directory
  path: data/MESH
parfiles:
  - class: File
    path: data/CF1/Par_file
  - class: File
    path: data/CF2/Par_file
reduction:
  script:
    class: File
    path: scripts/manipulate_shakemovie.py
stations:
  - class: File
    path: data/CF1/STATIONS
  - class: File
    path: data/CF2/STATIONS