cmtsolutions:
  - class: File
    path: data/CF1/CMTSOLUTION
  - class: File
    path: data/CF2/CMTSOLUTION
interpolation:
  processes: 32
  script:
    class: File
    path: scripts/mpi_moviedata2vtk.py
  step: 1000
meshdir:
  class: Directory
  path: data/MESH
parfile:
  class: File
  path: data/CF1/Par_file
reduction:
  script:
    class: File
    path: scripts/building_scenario_xdmf.py
stations:
  - class: File
    path: data/CF1/STATIONS
  - class: File
    path: data/CF2/STATIONS